//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace ADX4.Tools.Mappings {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4/Mappings")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.adx4.org/ADX/4/Mappings", IsNullable=false)]
    public partial class Mappings {
        
        private Substitution[] analyteField;
        
        private Substitution[] uOMField;
        
        private Substitution[] processingPathField;
        
        private AssayIdentification[] assaysField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Substitute", IsNullable=false)]
        public Substitution[] Analyte {
            get {
                return this.analyteField;
            }
            set {
                this.analyteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Substitute", IsNullable=false)]
        public Substitution[] UOM {
            get {
                return this.uOMField;
            }
            set {
                this.uOMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Substitute", IsNullable=false)]
        public Substitution[] ProcessingPath {
            get {
                return this.processingPathField;
            }
            set {
                this.processingPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Assay", IsNullable=false)]
        public AssayIdentification[] Assays {
            get {
                return this.assaysField;
            }
            set {
                this.assaysField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4/Mappings")]
    public partial class Substitution {
        
        private string nameField;
        
        private string withField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string With {
            get {
                return this.withField;
            }
            set {
                this.withField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4/Mappings")]
    public partial class AssayIdentification {
        
        private string assayTypeField;
        
        private string procedureCodeField;
        
        private string uOMField;
        
        private string analyteField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AssayType {
            get {
                return this.assayTypeField;
            }
            set {
                this.assayTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProcedureCode {
            get {
                return this.procedureCodeField;
            }
            set {
                this.procedureCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UOM {
            get {
                return this.uOMField;
            }
            set {
                this.uOMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Analyte {
            get {
                return this.analyteField;
            }
            set {
                this.analyteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
}
