//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADX4.Tools.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADX4.Tools.Languages.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        internal static string defBelowDetection {
            get {
                return ResourceManager.GetString("defBelowDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n/a.
        /// </summary>
        internal static string defNA {
            get {
                return ResourceManager.GetString("defNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        internal static string defOverRange {
            get {
                return ResourceManager.GetString("defOverRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PATH.
        /// </summary>
        internal static string fldProcessingPathKey {
            get {
                return ResourceManager.GetString("fldProcessingPathKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string fldSampleIdKey {
            get {
                return ResourceManager.GetString("fldSampleIdKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain of custody sample has not sample reference..
        /// </summary>
        internal static string valChainOfCustodySampleHasNoRef {
            get {
                return ResourceManager.GetString("valChainOfCustodySampleHasNoRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain of custody sample [{0}] is not listed in the list of available samples..
        /// </summary>
        internal static string valChainOfCustodySampleRefDoesNotExist {
            get {
                return ResourceManager.GetString("valChainOfCustodySampleRefDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement [{0}] has an unspecified status in an analysis for result [{1}]..
        /// </summary>
        internal static string valMeasurementHasAnUnspecifiedStatus {
            get {
                return ResourceManager.GetString("valMeasurementHasAnUnspecifiedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No measurements are specified in an analysis record for the result [{0}]..
        /// </summary>
        internal static string valNoAnalysisRecordMeasurementsSpecified {
            get {
                return ResourceManager.GetString("valNoAnalysisRecordMeasurementsSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No analyte is specified for a measurement in result [{0}]..
        /// </summary>
        internal static string valNoAnalyteSpecified {
            get {
                return ResourceManager.GetString("valNoAnalyteSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No chain of custody section is defined in the ADX document..
        /// </summary>
        internal static string valNoChainOfCustody {
            get {
                return ResourceManager.GetString("valNoChainOfCustody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No chain of custody batchs are defined in the ADX document..
        /// </summary>
        internal static string valNoChainOfCustodyBatch {
            get {
                return ResourceManager.GetString("valNoChainOfCustodyBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no ReceiveProcedure for the laboratory in the Chain Of Custody procedure..
        /// </summary>
        internal static string valNoChainOfCustodyLabReceiveProcedure {
            get {
                return ResourceManager.GetString("valNoChainOfCustodyLabReceiveProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no list of samples received by the laboratory in the Chain Of Custody section..
        /// </summary>
        internal static string valNoChainOfCustodyLabReceiveSamples {
            get {
                return ResourceManager.GetString("valNoChainOfCustodyLabReceiveSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No header section is defined in the ADX document..
        /// </summary>
        internal static string valNoHeader {
            get {
                return ResourceManager.GetString("valNoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No analytical report section is defined in the ADX header..
        /// </summary>
        internal static string valNoHeaderAnalyticalReport {
            get {
                return ResourceManager.GetString("valNoHeaderAnalyticalReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No lab job number is defined for the analytical report..
        /// </summary>
        internal static string valNoHeaderAnalyticalReportLabJobNo {
            get {
                return ResourceManager.GetString("valNoHeaderAnalyticalReportLabJobNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an unspecified status for the analytical report..
        /// </summary>
        internal static string valNoHeaderAnalyticalReportStatus {
            get {
                return ResourceManager.GetString("valNoHeaderAnalyticalReportStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No despatch section is defined in the ADX header..
        /// </summary>
        internal static string valNoHeaderDespatch {
            get {
                return ResourceManager.GetString("valNoHeaderDespatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The despatch is not specified..
        /// </summary>
        internal static string valNoHeaderDespatchSpecified {
            get {
                return ResourceManager.GetString("valNoHeaderDespatchSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No laboratory section is defined in the ADX header..
        /// </summary>
        internal static string valNoHeaderLaboratory {
            get {
                return ResourceManager.GetString("valNoHeaderLaboratory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No location reference is defined for the laboratory..
        /// </summary>
        internal static string valNoHeaderLaboratoryLocationRef {
            get {
                return ResourceManager.GetString("valNoHeaderLaboratoryLocationRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No samples owner section is defined in the ADX header..
        /// </summary>
        internal static string valNoHeaderSamplesOwner {
            get {
                return ResourceManager.GetString("valNoHeaderSamplesOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No location reference is defined for the samples owner..
        /// </summary>
        internal static string valNoHeaderSamplesOwnerLocationRef {
            get {
                return ResourceManager.GetString("valNoHeaderSamplesOwnerLocationRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No project is defined for the samples owner..
        /// </summary>
        internal static string valNoHeaderSamplesOwnerProject {
            get {
                return ResourceManager.GetString("valNoHeaderSamplesOwnerProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A processing group has an invalid, missing or empty identifier..
        /// </summary>
        internal static string valNoIdForProcessingGroup {
            get {
                return ResourceManager.GetString("valNoIdForProcessingGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement [{0} does not have a numeric value [{1}] in an analysis for result [{2}]..
        /// </summary>
        internal static string valNoMeasurementNumberValue {
            get {
                return ResourceManager.GetString("valNoMeasurementNumberValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement [{0}] does not have a procedure reference specified in an analysis for result [{1}]..
        /// </summary>
        internal static string valNoMeasurementProcedureRef {
            get {
                return ResourceManager.GetString("valNoMeasurementProcedureRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement [{0}] does not have a value in an analysis for result [{1}]..
        /// </summary>
        internal static string valNoMeasurementValue {
            get {
                return ResourceManager.GetString("valNoMeasurementValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement [{0}] does not have a units of measure (UOM) specified in an analysis for result [{1}]..
        /// </summary>
        internal static string valNoMeasurementValueUOM {
            get {
                return ResourceManager.GetString("valNoMeasurementValueUOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No processing history is defined for result [{0}]..
        /// </summary>
        internal static string valNoResultProcessingHistory {
            get {
                return ResourceManager.GetString("valNoResultProcessingHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results section is defined in the ADX document..
        /// </summary>
        internal static string valNoResults {
            get {
                return ResourceManager.GetString("valNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No processing groups are defined in the results section..
        /// </summary>
        internal static string valNoResultsProcessingGroups {
            get {
                return ResourceManager.GetString("valNoResultsProcessingGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results are defined in the processing group [{0}]..
        /// </summary>
        internal static string valNoResultsResult {
            get {
                return ResourceManager.GetString("valNoResultsResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a result with no sample references defined..
        /// </summary>
        internal static string valNoSampleRefDefinedForResult {
            get {
                return ResourceManager.GetString("valNoSampleRefDefinedForResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No samples section is defined in the ADX document..
        /// </summary>
        internal static string valNoSamples {
            get {
                return ResourceManager.GetString("valNoSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No samples are listed in the ADX document..
        /// </summary>
        internal static string valNoSamplesListed {
            get {
                return ResourceManager.GetString("valNoSamplesListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The analyte [{0}] is not recommended. Review the list of recommended analytes for a possible alternative..
        /// </summary>
        internal static string valNoStrictAnalyteSpecified {
            get {
                return ResourceManager.GetString("valNoStrictAnalyteSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unit of measure [{0}] is not recommended. Review the list of recommended units of measure for a possible alternative..
        /// </summary>
        internal static string valNoStrictUOMSpecified {
            get {
                return ResourceManager.GetString("valNoStrictUOMSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference material [{0}] has an unspecified category..
        /// </summary>
        internal static string valRefMatHasAnUnspecifiedCategory {
            get {
                return ResourceManager.GetString("valRefMatHasAnUnspecifiedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid material target [{0}]..
        /// </summary>
        internal static string valResultInvalidMaterialTarget {
            get {
                return ResourceManager.GetString("valResultInvalidMaterialTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple processing groups are included, however no parent processing path is defined on a result for sample [{0}] in processing group [{1}]..
        /// </summary>
        internal static string valResultNoParentProcessingPath {
            get {
                return ResourceManager.GetString("valResultNoParentProcessingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No processing history is defined on a result for sample [{0}]..
        /// </summary>
        internal static string valResultNoProcessingHistoryDefined {
            get {
                return ResourceManager.GetString("valResultNoProcessingHistoryDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Processing Path [{0}] is invalid since it was not found in the associated Processing History for sample {1}..
        /// </summary>
        internal static string valResultPathNotFoundInProcessingHistory {
            get {
                return ResourceManager.GetString("valResultPathNotFoundInProcessingHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a sample with an invalid, missing or empty identifier..
        /// </summary>
        internal static string valSampleExistsWithNoId {
            get {
                return ResourceManager.GetString("valSampleExistsWithNoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample [{0}] has an invalid, missing or empty type..
        /// </summary>
        internal static string valSampleExistsWithNoType {
            get {
                return ResourceManager.GetString("valSampleExistsWithNoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample [{0}] has an unspecified status..
        /// </summary>
        internal static string valSampleHasAnUnspecifiedStatus {
            get {
                return ResourceManager.GetString("valSampleHasAnUnspecifiedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to According to the Chain Of Custody, Sample [{0}] was not received by the laboratory. .
        /// </summary>
        internal static string valSampleNotReceivedByLaboratory {
            get {
                return ResourceManager.GetString("valSampleNotReceivedByLaboratory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A QA/QC sample [{0}] is potentially listed as a normal sample. If so then this should be listed as either Reference Material or derived from another sample via a Processing Path..
        /// </summary>
        internal static string valSamplePotentialQAQCListedAsSample {
            get {
                return ResourceManager.GetString("valSamplePotentialQAQCListedAsSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result sample reference, [{0}], is not listed in the Samples section..
        /// </summary>
        internal static string valUnknownResultSampleRef {
            get {
                return ResourceManager.GetString("valUnknownResultSampleRef", resourceCulture);
            }
        }
    }
}
