namespace NKD.Module
{
    partial class NKDModule
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            // 
            // NKDModule
            // 
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.FileData));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Location));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Province));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Account));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.AccountDiscount));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Address));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Applications));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ApplicationsView));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.AssayGroup));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.AssayGroupStandardTestResult));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.AssayGroupTest));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.AssayGroupTestResult));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.AssayGroupTestResultComment));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.AssayGroupTestResultDuplicate));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Asset));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.AssetAlias));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.AssetMaintenance));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.AssetWarranty));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.BlockModel));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.BlockModelBlock));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.BlockModelBlockData));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.BlockModelMetadata));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Casing));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Cementing));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Company));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.CompanyAccount));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.CompanyAddress));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.CompanyRelation));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.CompanyServer));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.CompanyView));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Compliance));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ComplianceTask));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ComplianceWorkType));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Contact));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ContactAddress));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Contract));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ContractAsset));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ContractCondition));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ContractConditionModel));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ContractConditionPart));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.CostEstimateModel));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Credit));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Currency));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Defect));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DefinitionIdentityTable));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DeliveryAdvice));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DeliveryAdviceItem));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Desurvey));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryAssetStatus));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Dictionary));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryAdjective));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryAlteration));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryAssayMethod));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryAssayStandard));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryAssayTest));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryAssayType));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryBasalContact));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryBedSpacing));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryCharacteristic));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryCharacteristicType));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryColour));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryCommodity));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryContractConditionType));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryCoreState));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryCostType));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryCountry));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryCountryState));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryDataStatus));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryDecontaminationStatus));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryDefectCompleteness));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryDefectContinuity));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryDefectSpacing));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryDefectType));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryDeliveryAdviceReason));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryDesurveyAlgorithmType));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryDeviceType));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryDimension));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryDipOrientationMethod));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryDomain));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryDomainAlias));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryDrillBitType));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryDrillCasingType));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryDrillFluid));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryDrillRigType));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryDrillSize));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryEstimatedStrength));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryEventType));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryFailureMode));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryFileType));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryFlowTestType));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryGasDetected));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryGeodeticDatum));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryGeophysicalLogType));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryGroup));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryGroupMembership));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryHeaderView));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryHeightDatum));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryHolePurpose));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryHoleStatus));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryHoleType));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryHorizon));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryHue));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryInfillMode));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryInfillType));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryIntervalStatus));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryLeaseApplicationType));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryLicenseType));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryLithologyInterrelation));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryLithologyQualifier));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryLithologyType));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryLocationType));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryMechanicalState));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryMineralAbundance));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryMineralAndFossilAbundance));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryMineralAndFossilAssociation));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryMineralAndFossilType));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryMineralForm));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryMineralStyle));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryMineralType));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryModel));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryModelCategory));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryModelRelation));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryModelStatus));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryMoistureSensitivity));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryPart));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryPartCategory));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryPartKit));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryPartKitItem));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryPartStatus));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryPlasticity));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryPly));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryPlyAlias));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryPointLoadTestType));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryPosition));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryProcedure));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryProfession));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryProvinceGroup));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryProvinceType));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryRelationType));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryRockMassUnitType));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionarySampleCategory));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionarySampleState));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionarySampleType));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionarySeam));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionarySeamAlias));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionarySedimentaryFeature));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryShade));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryShape));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryStratigraphy));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionarySurfaceRoughness));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionarySurveyAccuracy));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryTax));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryTexture));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryUnit));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryUnitType));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryUsageAuditType));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryWarrantyType));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryWeathering));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryWorkType));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryWorkTypeClass));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryWorkTypeRelation));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Drilling));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Experience));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ExperienceBasicView));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Geology));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Geophysics));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.GeophysicsData));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.GeophysicsMetadata));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Header));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.HeaderGeophysicalLog));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.HeaderHolePurpose));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.HeaderRelation));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.IdentityOwnerTable));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Instance));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.InstanceMetadataChangesTable));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.InstancePromotedPropertiesTable));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.InstancePromotedProperty));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.InstancesTable));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Interpretation));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.InterpretationData));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Invoice));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.InvoiceLine));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Journal));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.KeysTable));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Lease));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.LeaseApplication));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.License));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.LicenseAsset));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.LicenseAssetModelPart));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.LicenseHistory));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.LicenseView));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Lithology));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.LithologyAdjective));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.LithologySedimentaryFeature));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.LocationAlias));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.LocationData));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.LocationTrace));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.LockOwnersTable));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Membership));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.MembershipUsersView));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.MetaData));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.MetaDataRelation));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Mineralogy));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ModelCharacteristic));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ModelPart));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ModelPartKit));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ModelProcedure));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ModelProcedureTask));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ModelProcedureTaskPart));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ModelScheduleCycle));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ModelsCurrentView));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ModelStatusView));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ModelWarranty));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Opportunity));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Parameter));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ParameterDuplicate));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ParameterGroup));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.PartCharacteristic));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Paths));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Payment));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.PersonalizationAllUsers));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.PersonalizationPerUser));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.PointLoad));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.PrivateData));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Profile));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ProfilesView));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Project));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ProjectDeliverable));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ProjectModelsAwaitingAuthorisationView));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ProjectPlan));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ProjectPlanTask));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ProjectPlanTaskComplianceResponse));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ProjectPlanTaskData));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ProjectPlanTaskModel));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ProjectPlanTaskPart));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ProjectPlanTaskResponse));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ProjectPlanTaskResponseData));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ProjectPlanTaskWorker));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ProjectStatusView));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ProspectusProject));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ProspectusProjectCommodity));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ProvinceAlias));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ProvinceData));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ProvinceRelation));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.PurchaseOrder));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Recall));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.RecallModel));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.RecallModelAsset));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Recovery));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Roles));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.RolesView));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.RunnableInstancesTable));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Sample));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.SchemaVersions));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.SecurityBlacklist));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.SecurityWhitelist));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Server));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ServerApplication));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ServiceDeployment));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.ServiceDeploymentsTable));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.SupplierModel));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.SupplierPart));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Supply));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.SupplyItem));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.SupplyItemTax));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Survey));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.SurveyViewsView));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.sysdiagram));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Task));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.TaskData));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.TaskRelation));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Tenement));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.TenementCommodity));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.TenementProvince));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.TenementRelation));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Usage));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.UsageAuditView));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.UserData));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Users));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.UsersInRolesView));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.UsersView));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.Warehouse));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.WarehouseModel));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.WarehouseModelSupplier));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.WarehousePart));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.WarehousePartSupplier));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.WaterFlow));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.WebEvent_Events));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.WebPartState_PathsView));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.WebPartState_SharedView));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.WebPartState_UserView));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.WorkflowSchedule));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.WorkTypeView));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryCompositeStandardView));
            this.AdditionalExportedTypes.Add(typeof(NKD.Module.BusinessObjects.DictionaryCompositeCoalView));
            this.RequiredModuleTypes.Add(typeof(DevExpress.ExpressApp.SystemModule.SystemModule));

        }

        #endregion
    }
}
