//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace ADX4 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.adx4.org/ADX/4")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.adx4.org/ADX/4", IsNullable=false)]
    public partial class ADX {
        
        private Header headerField;
        
        private Protocols protocolsField;
        
        private AddressBook addressBookField;
        
        private ChainOfCustody chainOfCustodyField;
        
        private Samples samplesField;
        
        private ReferenceMaterials referenceMaterialsField;
        
        private Results resultsField;
        
        private string versionField;
        
        public ADX() {
            this.versionField = "4.1";
        }
        
        /// <remarks/>
        public Header Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        public Protocols Protocols {
            get {
                return this.protocolsField;
            }
            set {
                this.protocolsField = value;
            }
        }
        
        /// <remarks/>
        public AddressBook AddressBook {
            get {
                return this.addressBookField;
            }
            set {
                this.addressBookField = value;
            }
        }
        
        /// <remarks/>
        public ChainOfCustody ChainOfCustody {
            get {
                return this.chainOfCustodyField;
            }
            set {
                this.chainOfCustodyField = value;
            }
        }
        
        /// <remarks/>
        public Samples Samples {
            get {
                return this.samplesField;
            }
            set {
                this.samplesField = value;
            }
        }
        
        /// <remarks/>
        public ReferenceMaterials ReferenceMaterials {
            get {
                return this.referenceMaterialsField;
            }
            set {
                this.referenceMaterialsField = value;
            }
        }
        
        /// <remarks/>
        public Results Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class Header {
        
        private SamplesOwnerDetails samplesOwnerField;
        
        private LaboratoryDetails laboratoryField;
        
        private AnalyticalReportDetails analyticalReportField;
        
        private DespatchDetails despatchField;
        
        private BillingDetails billingField;
        
        private DocumentAuthorDetails documentAuthorField;
        
        private string commentsField;
        
        /// <remarks/>
        public SamplesOwnerDetails SamplesOwner {
            get {
                return this.samplesOwnerField;
            }
            set {
                this.samplesOwnerField = value;
            }
        }
        
        /// <remarks/>
        public LaboratoryDetails Laboratory {
            get {
                return this.laboratoryField;
            }
            set {
                this.laboratoryField = value;
            }
        }
        
        /// <remarks/>
        public AnalyticalReportDetails AnalyticalReport {
            get {
                return this.analyticalReportField;
            }
            set {
                this.analyticalReportField = value;
            }
        }
        
        /// <remarks/>
        public DespatchDetails Despatch {
            get {
                return this.despatchField;
            }
            set {
                this.despatchField = value;
            }
        }
        
        /// <remarks/>
        public BillingDetails Billing {
            get {
                return this.billingField;
            }
            set {
                this.billingField = value;
            }
        }
        
        /// <remarks/>
        public DocumentAuthorDetails DocumentAuthor {
            get {
                return this.documentAuthorField;
            }
            set {
                this.documentAuthorField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class SamplesOwnerDetails {
        
        private ProjectDetails projectField;
        
        private string commentsField;
        
        private string locationRefField;
        
        private string contactRefField;
        
        /// <remarks/>
        public ProjectDetails Project {
            get {
                return this.projectField;
            }
            set {
                this.projectField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LocationRef {
            get {
                return this.locationRefField;
            }
            set {
                this.locationRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ContactRef {
            get {
                return this.contactRefField;
            }
            set {
                this.contactRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class ProjectDetails {
        
        private string commentsField;
        
        private string idField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class Results {
        
        private ProcessingGroup[] processingGroupField;
        
        private string commentsField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProcessingGroup")]
        public ProcessingGroup[] ProcessingGroup {
            get {
                return this.processingGroupField;
            }
            set {
                this.processingGroupField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class ProcessingGroup {
        
        private Result[] resultField;
        
        private string commentsField;
        
        private string idField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Result")]
        public Result[] Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class Result {
        
        private ProcessingPath parentProcessingPathField;
        
        private SampleReference[] sampleField;
        
        private Process processingHistoryField;
        
        private AnalysisRecord[] analysisField;
        
        private string commentsField;
        
        /// <remarks/>
        public ProcessingPath ParentProcessingPath {
            get {
                return this.parentProcessingPathField;
            }
            set {
                this.parentProcessingPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Sample")]
        public SampleReference[] Sample {
            get {
                return this.sampleField;
            }
            set {
                this.sampleField = value;
            }
        }
        
        /// <remarks/>
        public Process ProcessingHistory {
            get {
                return this.processingHistoryField;
            }
            set {
                this.processingHistoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Analysis")]
        public AnalysisRecord[] Analysis {
            get {
                return this.analysisField;
            }
            set {
                this.analysisField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class ProcessingPath {
        
        private ProcessingTag[] tagField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Tag")]
        public ProcessingTag[] Tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class ProcessingTag {
        
        private string nameField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class SampleReference {
        
        private string idRefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IdRef {
            get {
                return this.idRefField;
            }
            set {
                this.idRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class Process {
        
        private MaterialDestination destinationField;
        
        private string descriptionField;
        
        private string commentsField;
        
        private string idField;
        
        private string codeField;
        
        /// <remarks/>
        public MaterialDestination Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class MaterialDestination {
        
        private Quantity massField;
        
        private MaterialTarget targetField;
        
        private string commentsField;
        
        private string nameField;
        
        private string typeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public Quantity Mass {
            get {
                return this.massField;
            }
            set {
                this.massField = value;
            }
        }
        
        /// <remarks/>
        public MaterialTarget Target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class Quantity {
        
        private string uOMField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UOM {
            get {
                return this.uOMField;
            }
            set {
                this.uOMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class MaterialTarget {
        
        private Procedure[] procedureField;
        
        private string protocolRefField;
        
        private string processRefField;
        
        private string procedureRefField;
        
        private string materialSourceRefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Procedure")]
        public Procedure[] Procedure {
            get {
                return this.procedureField;
            }
            set {
                this.procedureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProtocolRef {
            get {
                return this.protocolRefField;
            }
            set {
                this.protocolRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProcessRef {
            get {
                return this.processRefField;
            }
            set {
                this.processRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProcedureRef {
            get {
                return this.procedureRefField;
            }
            set {
                this.procedureRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MaterialSourceRef {
            get {
                return this.materialSourceRefField;
            }
            set {
                this.materialSourceRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RackPlacementProcedure))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DisposeProcedure))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReceiveProcedure))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SendProcedure))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CompositingProcedure))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WeighingProcedure))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenericProcedure))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DecompositionProcedure))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SplittingProcedure))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StorageProcedure))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ParticleSizeReductionProcedure))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ScreeningProcedure))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DryingProcedure))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AnalysisProcedure))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public abstract partial class Procedure {
        
        private string descriptionField;
        
        private string commentsField;
        
        private string idField;
        
        private string codeField;
        
        private string locationRefField;
        
        private string contactRefField;
        
        private System.DateTime timeStampField;
        
        private bool timeStampFieldSpecified;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LocationRef {
            get {
                return this.locationRefField;
            }
            set {
                this.locationRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ContactRef {
            get {
                return this.contactRefField;
            }
            set {
                this.contactRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TimeStampSpecified {
            get {
                return this.timeStampFieldSpecified;
            }
            set {
                this.timeStampFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class RackPlacementProcedure : Procedure {
        
        private string blockField;
        
        private string positionField;
        
        private MaterialDestination destinationField;
        
        /// <remarks/>
        public string Block {
            get {
                return this.blockField;
            }
            set {
                this.blockField = value;
            }
        }
        
        /// <remarks/>
        public string Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        public MaterialDestination Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class DisposeProcedure : Procedure {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class ReceiveProcedure : Procedure {
        
        private MaterialDestination destinationField;
        
        /// <remarks/>
        public MaterialDestination Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class SendProcedure : Procedure {
        
        private MaterialDestination destinationField;
        
        /// <remarks/>
        public MaterialDestination Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class CompositingProcedure : Procedure {
        
        private string methodField;
        
        private string equipmentField;
        
        private MaterialSource[] sourceField;
        
        private MaterialDestination destinationField;
        
        /// <remarks/>
        public string Method {
            get {
                return this.methodField;
            }
            set {
                this.methodField = value;
            }
        }
        
        /// <remarks/>
        public string Equipment {
            get {
                return this.equipmentField;
            }
            set {
                this.equipmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Source")]
        public MaterialSource[] Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public MaterialDestination Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class MaterialSource {
        
        private string idField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class WeighingProcedure : Procedure {
        
        private string methodField;
        
        private string equipmentField;
        
        private Quantity massField;
        
        private MaterialDestination destinationField;
        
        /// <remarks/>
        public string Method {
            get {
                return this.methodField;
            }
            set {
                this.methodField = value;
            }
        }
        
        /// <remarks/>
        public string Equipment {
            get {
                return this.equipmentField;
            }
            set {
                this.equipmentField = value;
            }
        }
        
        /// <remarks/>
        public Quantity Mass {
            get {
                return this.massField;
            }
            set {
                this.massField = value;
            }
        }
        
        /// <remarks/>
        public MaterialDestination Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class GenericProcedure : Procedure {
        
        private MaterialDestination destinationField;
        
        /// <remarks/>
        public MaterialDestination Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class DecompositionProcedure : Procedure {
        
        private string methodField;
        
        private Quantity weightField;
        
        private Quantity temperatureField;
        
        private string durationField;
        
        private string agitationField;
        
        private MaterialDestination destinationField;
        
        private string chemicalsField;
        
        /// <remarks/>
        public string Method {
            get {
                return this.methodField;
            }
            set {
                this.methodField = value;
            }
        }
        
        /// <remarks/>
        public Quantity Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        public Quantity Temperature {
            get {
                return this.temperatureField;
            }
            set {
                this.temperatureField = value;
            }
        }
        
        /// <remarks/>
        public string Duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        public string Agitation {
            get {
                return this.agitationField;
            }
            set {
                this.agitationField = value;
            }
        }
        
        /// <remarks/>
        public MaterialDestination Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        public string Chemicals {
            get {
                return this.chemicalsField;
            }
            set {
                this.chemicalsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class SplittingProcedure : Procedure {
        
        private string methodField;
        
        private string equipmentField;
        
        private MaterialDestination[] destinationField;
        
        /// <remarks/>
        public string Method {
            get {
                return this.methodField;
            }
            set {
                this.methodField = value;
            }
        }
        
        /// <remarks/>
        public string Equipment {
            get {
                return this.equipmentField;
            }
            set {
                this.equipmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Destination")]
        public MaterialDestination[] Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class StorageProcedure : Procedure {
        
        private MaterialDestination destinationField;
        
        /// <remarks/>
        public MaterialDestination Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class ParticleSizeReductionProcedure : Procedure {
        
        private string methodField;
        
        private Screen screenField;
        
        private string equipmentField;
        
        private decimal percentField;
        
        private bool percentFieldSpecified;
        
        private MaterialDestination destinationField;
        
        /// <remarks/>
        public string Method {
            get {
                return this.methodField;
            }
            set {
                this.methodField = value;
            }
        }
        
        /// <remarks/>
        public Screen Screen {
            get {
                return this.screenField;
            }
            set {
                this.screenField = value;
            }
        }
        
        /// <remarks/>
        public string Equipment {
            get {
                return this.equipmentField;
            }
            set {
                this.equipmentField = value;
            }
        }
        
        /// <remarks/>
        public decimal Percent {
            get {
                return this.percentField;
            }
            set {
                this.percentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PercentSpecified {
            get {
                return this.percentFieldSpecified;
            }
            set {
                this.percentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public MaterialDestination Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class Screen {
        
        private string uOMField;
        
        private string seriesField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UOM {
            get {
                return this.uOMField;
            }
            set {
                this.uOMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Series {
            get {
                return this.seriesField;
            }
            set {
                this.seriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class ScreeningProcedure : Procedure {
        
        private Screen screenField;
        
        private MaterialDestination aboveScreenField;
        
        private MaterialDestination belowScreenField;
        
        private ScreenCondition conditionField;
        
        private bool conditionFieldSpecified;
        
        /// <remarks/>
        public Screen Screen {
            get {
                return this.screenField;
            }
            set {
                this.screenField = value;
            }
        }
        
        /// <remarks/>
        public MaterialDestination AboveScreen {
            get {
                return this.aboveScreenField;
            }
            set {
                this.aboveScreenField = value;
            }
        }
        
        /// <remarks/>
        public MaterialDestination BelowScreen {
            get {
                return this.belowScreenField;
            }
            set {
                this.belowScreenField = value;
            }
        }
        
        /// <remarks/>
        public ScreenCondition Condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ConditionSpecified {
            get {
                return this.conditionFieldSpecified;
            }
            set {
                this.conditionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4/Dictionary")]
    public enum ScreenCondition {
        
        /// <remarks/>
        Unspecified,
        
        /// <remarks/>
        Wet,
        
        /// <remarks/>
        Dry,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class DryingProcedure : Procedure {
        
        private string methodField;
        
        private Quantity temperatureField;
        
        private string durationField;
        
        private string equipmentField;
        
        private MaterialDestination destinationField;
        
        /// <remarks/>
        public string Method {
            get {
                return this.methodField;
            }
            set {
                this.methodField = value;
            }
        }
        
        /// <remarks/>
        public Quantity Temperature {
            get {
                return this.temperatureField;
            }
            set {
                this.temperatureField = value;
            }
        }
        
        /// <remarks/>
        public string Duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        public string Equipment {
            get {
                return this.equipmentField;
            }
            set {
                this.equipmentField = value;
            }
        }
        
        /// <remarks/>
        public MaterialDestination Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class AnalysisProcedure : Procedure {
        
        private string propertyField;
        
        private string uOMField;
        
        private Quantity belowDetectionLimitField;
        
        private Quantity overRangeLimitField;
        
        private AnalysisMethod methodField;
        
        private MaterialDestination destinationField;
        
        /// <remarks/>
        public string Property {
            get {
                return this.propertyField;
            }
            set {
                this.propertyField = value;
            }
        }
        
        /// <remarks/>
        public string UOM {
            get {
                return this.uOMField;
            }
            set {
                this.uOMField = value;
            }
        }
        
        /// <remarks/>
        public Quantity BelowDetectionLimit {
            get {
                return this.belowDetectionLimitField;
            }
            set {
                this.belowDetectionLimitField = value;
            }
        }
        
        /// <remarks/>
        public Quantity OverRangeLimit {
            get {
                return this.overRangeLimitField;
            }
            set {
                this.overRangeLimitField = value;
            }
        }
        
        /// <remarks/>
        public AnalysisMethod Method {
            get {
                return this.methodField;
            }
            set {
                this.methodField = value;
            }
        }
        
        /// <remarks/>
        public MaterialDestination Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class AnalysisMethod {
        
        private string techniqueField;
        
        private string equipmentField;
        
        private string commentsField;
        
        /// <remarks/>
        public string Technique {
            get {
                return this.techniqueField;
            }
            set {
                this.techniqueField = value;
            }
        }
        
        /// <remarks/>
        public string Equipment {
            get {
                return this.equipmentField;
            }
            set {
                this.equipmentField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class AnalysisRecord {
        
        private ProcessingPath fullProcessingPathField;
        
        private Measurement[] measurementField;
        
        private string commentsField;
        
        private string idField;
        
        /// <remarks/>
        public ProcessingPath FullProcessingPath {
            get {
                return this.fullProcessingPathField;
            }
            set {
                this.fullProcessingPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Measurement")]
        public Measurement[] Measurement {
            get {
                return this.measurementField;
            }
            set {
                this.measurementField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class Measurement {
        
        private Quantity valueField;
        
        private string commentsField;
        
        private string propertyField;
        
        private MeasurementStatus statusField;
        
        private bool statusFieldSpecified;
        
        private string procedureRefField;
        
        private string locationRefField;
        
        /// <remarks/>
        public Quantity Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Property {
            get {
                return this.propertyField;
            }
            set {
                this.propertyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MeasurementStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProcedureRef {
            get {
                return this.procedureRefField;
            }
            set {
                this.procedureRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LocationRef {
            get {
                return this.locationRefField;
            }
            set {
                this.locationRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4/Dictionary")]
    public enum MeasurementStatus {
        
        /// <remarks/>
        Unspecified,
        
        /// <remarks/>
        Calculated,
        
        /// <remarks/>
        Detected,
        
        /// <remarks/>
        BelowDetection,
        
        /// <remarks/>
        OverRange,
        
        /// <remarks/>
        Insufficient,
        
        /// <remarks/>
        NotAnalysed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class ReferenceMaterials {
        
        private ProcessingGroup[] processingGroupField;
        
        private string commentsField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProcessingGroup")]
        public ProcessingGroup[] ProcessingGroup {
            get {
                return this.processingGroupField;
            }
            set {
                this.processingGroupField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class AnalysisReference {
        
        private string idRefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IdRef {
            get {
                return this.idRefField;
            }
            set {
                this.idRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReferenceMaterial))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class Sample {
        
        private string commentsField;
        
        private string idField;
        
        private string typeField;
        
        private SampleStatus statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SampleStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4/Dictionary")]
    public enum SampleStatus {
        
        /// <remarks/>
        Unspecified,
        
        /// <remarks/>
        Available,
        
        /// <remarks/>
        Destroyed,
        
        /// <remarks/>
        Missing,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class ReferenceMaterial : Sample {
        
        private ReferenceMaterialCategory categoryField;
        
        private AnalysisReference knownAnalysisField;
        
        /// <remarks/>
        public ReferenceMaterialCategory Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        public AnalysisReference KnownAnalysis {
            get {
                return this.knownAnalysisField;
            }
            set {
                this.knownAnalysisField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4/Dictionary")]
    public enum ReferenceMaterialCategory {
        
        /// <remarks/>
        Unspecified,
        
        /// <remarks/>
        Standard,
        
        /// <remarks/>
        Blank,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class Samples {
        
        private Sample[] sampleField;
        
        private string commentsField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Sample")]
        public Sample[] Sample {
            get {
                return this.sampleField;
            }
            set {
                this.sampleField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class ChainOfCustodySample {
        
        private SampleReference[] sampleField;
        
        private ProcessingPath processingPathField;
        
        private string commentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Sample")]
        public SampleReference[] Sample {
            get {
                return this.sampleField;
            }
            set {
                this.sampleField = value;
            }
        }
        
        /// <remarks/>
        public ProcessingPath ProcessingPath {
            get {
                return this.processingPathField;
            }
            set {
                this.processingPathField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class ChainOfCustodyBatch {
        
        private Process historyField;
        
        private ChainOfCustodySample[] sampleMaterialField;
        
        private string commentsField;
        
        private string idField;
        
        /// <remarks/>
        public Process History {
            get {
                return this.historyField;
            }
            set {
                this.historyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SampleMaterial")]
        public ChainOfCustodySample[] SampleMaterial {
            get {
                return this.sampleMaterialField;
            }
            set {
                this.sampleMaterialField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class ChainOfCustody {
        
        private ChainOfCustodyBatch[] batchField;
        
        private string commentsField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Batch")]
        public ChainOfCustodyBatch[] Batch {
            get {
                return this.batchField;
            }
            set {
                this.batchField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class LocationDetails {
        
        private string companyField;
        
        private string officeField;
        
        private string descriptionField;
        
        private string telephoneField;
        
        private string emailField;
        
        private string addressField;
        
        private string cityField;
        
        private string stateField;
        
        private string countryField;
        
        private string postalCodeField;
        
        private string commentsField;
        
        private string idField;
        
        private string contactRefField;
        
        /// <remarks/>
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        public string Office {
            get {
                return this.officeField;
            }
            set {
                this.officeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Telephone {
            get {
                return this.telephoneField;
            }
            set {
                this.telephoneField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ContactRef {
            get {
                return this.contactRefField;
            }
            set {
                this.contactRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class ContactDetails {
        
        private string contactNameField;
        
        private string roleField;
        
        private string telephoneField;
        
        private string emailField;
        
        private string commentsField;
        
        private string idField;
        
        private string locationRefField;
        
        /// <remarks/>
        public string ContactName {
            get {
                return this.contactNameField;
            }
            set {
                this.contactNameField = value;
            }
        }
        
        /// <remarks/>
        public string Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
        
        /// <remarks/>
        public string Telephone {
            get {
                return this.telephoneField;
            }
            set {
                this.telephoneField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LocationRef {
            get {
                return this.locationRefField;
            }
            set {
                this.locationRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class AddressBook {
        
        private ContactDetails[] contactField;
        
        private LocationDetails[] locationField;
        
        private string commentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Contact")]
        public ContactDetails[] Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Location")]
        public LocationDetails[] Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class Protocol {
        
        private Process[] processField;
        
        private string descriptionField;
        
        private string commentsField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Process")]
        public Process[] Process {
            get {
                return this.processField;
            }
            set {
                this.processField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class Protocols {
        
        private Protocol[] protocolField;
        
        private string commentsField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Protocol")]
        public Protocol[] Protocol {
            get {
                return this.protocolField;
            }
            set {
                this.protocolField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class DocumentAuthorDetails {
        
        private string authorRefField;
        
        private System.DateTime createdOnField;
        
        private string commentsField;
        
        private string idField;
        
        /// <remarks/>
        public string AuthorRef {
            get {
                return this.authorRefField;
            }
            set {
                this.authorRefField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreatedOn {
            get {
                return this.createdOnField;
            }
            set {
                this.createdOnField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class BillingDetails {
        
        private string commentsField;
        
        private string codeField;
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class DespatchDetails {
        
        private string despatchNoField;
        
        private Process processingInstructionsField;
        
        private string commentsField;
        
        /// <remarks/>
        public string DespatchNo {
            get {
                return this.despatchNoField;
            }
            set {
                this.despatchNoField = value;
            }
        }
        
        /// <remarks/>
        public Process ProcessingInstructions {
            get {
                return this.processingInstructionsField;
            }
            set {
                this.processingInstructionsField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class AnalyticalReportDetails {
        
        private string labJobField;
        
        private AnalyticalReportStatus statusField;
        
        private System.DateTime statusDateField;
        
        private string labInvoiceNoField;
        
        private string referenceLabJobField;
        
        private string commentsField;
        
        /// <remarks/>
        public string LabJob {
            get {
                return this.labJobField;
            }
            set {
                this.labJobField = value;
            }
        }
        
        /// <remarks/>
        public AnalyticalReportStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StatusDate {
            get {
                return this.statusDateField;
            }
            set {
                this.statusDateField = value;
            }
        }
        
        /// <remarks/>
        public string LabInvoiceNo {
            get {
                return this.labInvoiceNoField;
            }
            set {
                this.labInvoiceNoField = value;
            }
        }
        
        /// <remarks/>
        public string ReferenceLabJob {
            get {
                return this.referenceLabJobField;
            }
            set {
                this.referenceLabJobField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4/Dictionary")]
    public enum AnalyticalReportStatus {
        
        /// <remarks/>
        Unspecified,
        
        /// <remarks/>
        Preliminary,
        
        /// <remarks/>
        Certified,
        
        /// <remarks/>
        CertificateCorrection,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4")]
    public partial class LaboratoryDetails {
        
        private string commentsField;
        
        private string locationRefField;
        
        private string contactRefField;
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LocationRef {
            get {
                return this.locationRefField;
            }
            set {
                this.locationRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ContactRef {
            get {
                return this.contactRefField;
            }
            set {
                this.contactRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.adx4.org/ADX/4")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.adx4.org/ADX/4", IsNullable=false)]
    public partial class ADXDictionaryStrict {
        
        private PropertyTypeStrict propertyTypeExampleField;
        
        private UOMStrict uOMExampleField;
        
        /// <remarks/>
        public PropertyTypeStrict PropertyTypeExample {
            get {
                return this.propertyTypeExampleField;
            }
            set {
                this.propertyTypeExampleField = value;
            }
        }
        
        /// <remarks/>
        public UOMStrict UOMExample {
            get {
                return this.uOMExampleField;
            }
            set {
                this.uOMExampleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4/Dictionary")]
    public enum PropertyTypeStrict {
        
        /// <remarks/>
        Unspecified,
        
        /// <remarks/>
        Ag,
        
        /// <remarks/>
        Al,
        
        /// <remarks/>
        Al2O3,
        
        /// <remarks/>
        Ar,
        
        /// <remarks/>
        As,
        
        /// <remarks/>
        Au,
        
        /// <remarks/>
        B,
        
        /// <remarks/>
        Ba,
        
        /// <remarks/>
        BaO,
        
        /// <remarks/>
        Be,
        
        /// <remarks/>
        Bi,
        
        /// <remarks/>
        BO3,
        
        /// <remarks/>
        Br,
        
        /// <remarks/>
        C,
        
        /// <remarks/>
        Ca,
        
        /// <remarks/>
        CaO,
        
        /// <remarks/>
        Cd,
        
        /// <remarks/>
        Ce,
        
        /// <remarks/>
        Cl,
        
        /// <remarks/>
        Co,
        
        /// <remarks/>
        CO2,
        
        /// <remarks/>
        Cr,
        
        /// <remarks/>
        Cr2O3,
        
        /// <remarks/>
        Cs,
        
        /// <remarks/>
        Cu,
        
        /// <remarks/>
        TCu,
        
        /// <remarks/>
        SCu,
        
        /// <remarks/>
        Dy,
        
        /// <remarks/>
        Er,
        
        /// <remarks/>
        Eu,
        
        /// <remarks/>
        F,
        
        /// <remarks/>
        Fe,
        
        /// <remarks/>
        Fe2O3,
        
        /// <remarks/>
        FeO,
        
        /// <remarks/>
        Ga,
        
        /// <remarks/>
        Gd,
        
        /// <remarks/>
        Ge,
        
        /// <remarks/>
        H2O,
        
        /// <remarks/>
        He,
        
        /// <remarks/>
        Hf,
        
        /// <remarks/>
        Hg,
        
        /// <remarks/>
        Ho,
        
        /// <remarks/>
        I,
        
        /// <remarks/>
        In,
        
        /// <remarks/>
        Ir,
        
        /// <remarks/>
        K,
        
        /// <remarks/>
        K2O,
        
        /// <remarks/>
        Kr,
        
        /// <remarks/>
        La,
        
        /// <remarks/>
        Li,
        
        /// <remarks/>
        LOI,
        
        /// <remarks/>
        Lu,
        
        /// <remarks/>
        Mg,
        
        /// <remarks/>
        MgO,
        
        /// <remarks/>
        Mn,
        
        /// <remarks/>
        MnO,
        
        /// <remarks/>
        Mo,
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        Na,
        
        /// <remarks/>
        Na2O,
        
        /// <remarks/>
        Nb,
        
        /// <remarks/>
        Nd,
        
        /// <remarks/>
        Ne,
        
        /// <remarks/>
        Ni,
        
        /// <remarks/>
        NiO,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OH-")]
        OH,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OH+")]
        OH1,
        
        /// <remarks/>
        Os,
        
        /// <remarks/>
        P,
        
        /// <remarks/>
        P2O5,
        
        /// <remarks/>
        Pb,
        
        /// <remarks/>
        Pd,
        
        /// <remarks/>
        Pm,
        
        /// <remarks/>
        Pr,
        
        /// <remarks/>
        Pt,
        
        /// <remarks/>
        Ra,
        
        /// <remarks/>
        Rb,
        
        /// <remarks/>
        Re,
        
        /// <remarks/>
        Rh,
        
        /// <remarks/>
        Rn,
        
        /// <remarks/>
        Ru,
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        S2,
        
        /// <remarks/>
        Sb,
        
        /// <remarks/>
        Sc,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("SCu")]
        SCu1,
        
        /// <remarks/>
        Se,
        
        /// <remarks/>
        Si,
        
        /// <remarks/>
        SiO2,
        
        /// <remarks/>
        Sm,
        
        /// <remarks/>
        Sn,
        
        /// <remarks/>
        SO3,
        
        /// <remarks/>
        SO4,
        
        /// <remarks/>
        Sr,
        
        /// <remarks/>
        Ta,
        
        /// <remarks/>
        Tb,
        
        /// <remarks/>
        Tc,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("TCu")]
        TCu1,
        
        /// <remarks/>
        Te,
        
        /// <remarks/>
        Th,
        
        /// <remarks/>
        Ti,
        
        /// <remarks/>
        TiO2,
        
        /// <remarks/>
        Tl,
        
        /// <remarks/>
        Tm,
        
        /// <remarks/>
        U,
        
        /// <remarks/>
        V,
        
        /// <remarks/>
        V2O5,
        
        /// <remarks/>
        W,
        
        /// <remarks/>
        Y,
        
        /// <remarks/>
        Yb,
        
        /// <remarks/>
        Zn,
        
        /// <remarks/>
        Zr,
        
        /// <remarks/>
        ZrO2,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adx4.org/ADX/4/Dictionary")]
    public enum UOMStrict {
        
        /// <remarks/>
        Unspecified,
        
        /// <remarks/>
        m,
        
        /// <remarks/>
        kg,
        
        /// <remarks/>
        s,
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        K,
        
        /// <remarks/>
        mol,
        
        /// <remarks/>
        cd,
        
        /// <remarks/>
        rad,
        
        /// <remarks/>
        sr,
        
        /// <remarks/>
        degC,
        
        /// <remarks/>
        f,
        
        /// <remarks/>
        C,
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("kg/m3")]
        kgm3,
        
        /// <remarks/>
        V,
        
        /// <remarks/>
        ohm,
        
        /// <remarks/>
        J,
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        Hz,
        
        /// <remarks/>
        lx,
        
        /// <remarks/>
        lm,
        
        /// <remarks/>
        Wb,
        
        /// <remarks/>
        T,
        
        /// <remarks/>
        W,
        
        /// <remarks/>
        P,
        
        /// <remarks/>
        Bq,
        
        /// <remarks/>
        Gy,
        
        /// <remarks/>
        Sv,
        
        /// <remarks/>
        kat,
        
        /// <remarks/>
        g,
        
        /// <remarks/>
        min,
        
        /// <remarks/>
        h,
        
        /// <remarks/>
        d,
        
        /// <remarks/>
        ha,
        
        /// <remarks/>
        l,
        
        /// <remarks/>
        t,
        
        /// <remarks/>
        Np,
        
        /// <remarks/>
        B,
        
        /// <remarks/>
        eV,
        
        /// <remarks/>
        u,
        
        /// <remarks/>
        ua,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("nautical mile")]
        nauticalmile,
        
        /// <remarks/>
        knot,
        
        /// <remarks/>
        a,
        
        /// <remarks/>
        bar,
        
        /// <remarks/>
        Å,
        
        /// <remarks/>
        Ci,
        
        /// <remarks/>
        R,
        
        /// <remarks/>
        rd,
        
        /// <remarks/>
        rem,
        
        /// <remarks/>
        ppm,
        
        /// <remarks/>
        ppb,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("%")]
        Item,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("g/l")]
        gl,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("kg/m3")]
        kgm31,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("g/t")]
        gt,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("g/cm3")]
        gcm3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("mg/l")]
        mgl,
    }
}
