//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NKD.Module.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NKD.Module.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACKUP DATABASE [NKD] TO  DISK = N&apos;{0}&apos; WITH NOFORMAT, NOINIT,  NAME = N&apos;NKD-Full Database Backup&apos;, SKIP, NOREWIND, NOUNLOAD,  STATS = 10
        ///GO.
        /// </summary>
        internal static string NKDBackup {
            get {
                return ResourceManager.GetString("NKDBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE master
        /// GO
        ///
        /// ALTER DATABASE NKD
        /// SET OFFLINE WITH ROLLBACK IMMEDIATE
        /// ALTER DATABASE NKD
        /// SET ONLINE
        /// GO
        ///
        /// USE NKD
        /// GO.
        /// </summary>
        internal static string NKDClose {
            get {
                return ResourceManager.GetString("NKDClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [master]
        ///GO
        ///RESTORE DATABASE [NKD] FROM  DISK = N&apos;{0}&apos; WITH MOVE &apos;NKD&apos; TO &apos;{1}&apos;,  MOVE &apos;NKD_Log&apos; TO &apos;{2}&apos; --, REPLACE, NORECOVERY, FILE = 1,  NOUNLOAD,  STATS = 5
        ///GO.
        /// </summary>
        internal static string NKDRestore {
            get {
                return ResourceManager.GetString("NKDRestore", resourceCulture);
            }
        }
    }
}
